name: manage-azure-policy-a489de08
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/tag_prod_to_BackupVault02_c6b7eaa5-6c49-4bd8-99a3-0b41a0a77c06/**'
#      - .github/workflows/manage-azure-policy-a489de08.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a489de08}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/tag_prod_to_BackupVault02_c6b7eaa5-6c49-4bd8-99a3-0b41a0a77c06/**
